const foods = [
  { name: "Pizza", price: 200 },
  { name: "Burger", price: 120 },
  { name: "Dosa", price: 80 },
  { name: "Pani Puri", price: 40 },
  { name: "Biryani", price: 250 },
  { name: "Samosa", price: 20 },
  { name: "Vada Pav", price: 10 },
  { name: "French Fries", price: 90 },
  { name: "Fried Rice", price: 140 },
  { name: "Chole Bhature", price: 180 },
  { name: "Idli Sambhar", price: 70 },
  { name: "Pasta", price: 160 },
  { name: "Momos", price: 110 },
  { name: "Paneer Tikka", price: 230 },
  { name: "Chicken Roll", price: 130 },
  { name: "Poha", price: 30 },
  { name: "Maggi", price: 50 },
  { name: "Paratha", price: 60 },
  { name: "Chicken Biryani", price: 280 },
  { name: "Egg Curry", price: 120 },
  { name: "Paneer Biryani", price: 240 },
  { name: "Aloo Tikki", price: 35 },
  { name: "Manchurian", price: 150 },
  { name: "Noodles", price: 130 },
  { name: "Chai", price: 15 },
  { name: "Cold Coffee", price: 120 },
  { name: "Lassi", price: 90 },
  { name: "Gulab Jamun", price: 50 },
  { name: "Ice Cream", price: 70 },
  { name: "Waffles", price: 180 }
];

export default foods;
